import type { PresetProfile } from '../types';

/**
 * Pre-configured profiles for common facility types.
 * Based on COMCAM market analysis 2024.
 */
export const PRESETS: PresetProfile[] = [
  {
    name: 'Klein hotel',
    description: '50-100 kamers, jaarverbruik ~200.000 kWh',
    sector: 'hospitality',
    batteryConfig: {
      capacityKwh: 100,
      powerKw: 50,
      costPerKwh: 550,
      installationCost: 15000,
      annualMaintenanceCost: 2000,
      lifespanYears: 15,
      roundTripEfficiency: 0.89,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 80,
      annualConsumptionKwh: 200000,
      connectionCapacityKw: 100,
    },
  },
  {
    name: 'Groot hotel',
    description: '200+ kamers, jaarverbruik ~600.000 kWh',
    sector: 'hospitality',
    batteryConfig: {
      capacityKwh: 300,
      powerKw: 150,
      costPerKwh: 500,
      installationCost: 35000,
      annualMaintenanceCost: 5000,
      lifespanYears: 15,
      roundTripEfficiency: 0.9,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 250,
      annualConsumptionKwh: 600000,
      connectionCapacityKw: 300,
    },
  },
  {
    name: 'Ziekenhuis',
    description: 'Middelgroot ziekenhuis, jaarverbruik ~2.000.000 kWh',
    sector: 'healthcare',
    batteryConfig: {
      capacityKwh: 500,
      powerKw: 250,
      costPerKwh: 480,
      installationCost: 50000,
      annualMaintenanceCost: 8000,
      lifespanYears: 15,
      roundTripEfficiency: 0.9,
      annualDegradation: 0.02,
      cycleLife: 7000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 800,
      annualConsumptionKwh: 2000000,
      connectionCapacityKw: 1000,
    },
  },
  {
    name: 'Zorginstelling',
    description: 'Verpleeghuis/zorgcentrum, jaarverbruik ~400.000 kWh',
    sector: 'healthcare',
    batteryConfig: {
      capacityKwh: 150,
      powerKw: 75,
      costPerKwh: 530,
      installationCost: 20000,
      annualMaintenanceCost: 3000,
      lifespanYears: 15,
      roundTripEfficiency: 0.89,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 150,
      annualConsumptionKwh: 400000,
      connectionCapacityKw: 200,
    },
  },
  {
    name: 'Kantoorpand',
    description: 'Middelgroot kantoor, jaarverbruik ~150.000 kWh',
    sector: 'kantoor',
    batteryConfig: {
      capacityKwh: 75,
      powerKw: 40,
      costPerKwh: 550,
      installationCost: 12000,
      annualMaintenanceCost: 1500,
      lifespanYears: 15,
      roundTripEfficiency: 0.89,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 60,
      annualConsumptionKwh: 150000,
      connectionCapacityKw: 80,
    },
  },
  {
    name: 'Winkelcentrum',
    description: 'Winkelcentrum, jaarverbruik ~500.000 kWh',
    sector: 'retail',
    batteryConfig: {
      capacityKwh: 200,
      powerKw: 100,
      costPerKwh: 520,
      installationCost: 25000,
      annualMaintenanceCost: 4000,
      lifespanYears: 15,
      roundTripEfficiency: 0.89,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 200,
      annualConsumptionKwh: 500000,
      connectionCapacityKw: 250,
    },
  },
  {
    name: 'Productiebedrijf',
    description: 'MKB industrie, jaarverbruik ~800.000 kWh',
    sector: 'industrie',
    batteryConfig: {
      capacityKwh: 250,
      powerKw: 125,
      costPerKwh: 500,
      installationCost: 30000,
      annualMaintenanceCost: 5000,
      lifespanYears: 15,
      roundTripEfficiency: 0.90,
      annualDegradation: 0.025,
      cycleLife: 6000,
      depthOfDischarge: 0.9,
    },
    energyProfile: {
      peakDemandKw: 350,
      annualConsumptionKwh: 800000,
      connectionCapacityKw: 400,
    },
  },
];
